/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AAffix: typeof import('@arco-design/web-vue')['Affix']
    AButton: typeof import('@arco-design/web-vue')['Button']
    ADoption: typeof import('@arco-design/web-vue')['Doption']
    ADropdown: typeof import('@arco-design/web-vue')['Dropdown']
    AImage: typeof import('@arco-design/web-vue')['Image']
    ALayout: typeof import('@arco-design/web-vue')['Layout']
    ALayoutContent: typeof import('@arco-design/web-vue')['LayoutContent']
    ALayoutFooter: typeof import('@arco-design/web-vue')['LayoutFooter']
    ALayoutHeader: typeof import('@arco-design/web-vue')['LayoutHeader']
    ALayoutSider: typeof import('@arco-design/web-vue')['LayoutSider']
    ALink: typeof import('@arco-design/web-vue')['Link']
    AMenu: typeof import('@arco-design/web-vue')['Menu']
    AMenuItem: typeof import('@arco-design/web-vue')['MenuItem']
    ASubMenu: typeof import('@arco-design/web-vue')['SubMenu']
    ATrigger: typeof import('@arco-design/web-vue')['Trigger']
    DefaultLayout: typeof import('./src/layout/switch/DefaultLayout.vue')['default']
    Footer: typeof import('./src/layout/components/Footer.vue')['default']
    Github: typeof import('./src/layout/components/Github.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconMaterialSymbolsCheckSmall: typeof import('~icons/material-symbols/check-small')['default']
    IconMdiGithub: typeof import('~icons/mdi/github')['default']
    IconRiHammerFill: typeof import('~icons/ri/hammer-fill')['default']
    Logo: typeof import('./src/layout/components/Logo.vue')['default']
    Menu: typeof import('./src/layout/components/Menu/index.vue')['default']
    MenuItem: typeof import('./src/layout/components/Menu/MenuItem.vue')['default']
    Navbar: typeof import('./src/layout/components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarLayout: typeof import('./src/layout/switch/SidebarLayout.vue')['default']
    SwitchIndex: typeof import('./src/layout/SwitchIndex.vue')['default']
    SwitchLayout: typeof import('./src/layout/components/SwitchLayout.vue')['default']
    Versions: typeof import('./src/components/Versions.vue')['default']
  }
}
